services:
  optimizer:
    build: 
      context: . 
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    command: 
      - "01_ASPaeroFlow/main.py"
      - "--seed=11904657"
      - "--max-number-sectors=100000"
      - "--timestep-granularity=1"
      - "--controller-enabled=True"
      - "--data-dir=01_ASPaeroFlow/controller_folder/CENTRAL-EUROPE-7x7"
      - "--encoding-path=01_ASPaeroFlow/encoding.lp"
      - "--controller-hostname=0.0.0.0"
    expose:
      - "8080" 

  controller:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    command: 
      - "07_heuristic_controller/controller_mockup_2.py"
      - "--default-hostname=0.0.0.0"
    expose:
      - "8081" 
    depends_on:
      - clinguin-backend
      - optimizer

  clinguin-backend:
    build:
      context: ../ASPaeroFlow-XAI
      dockerfile: Dockerfile
    entrypoint: ["micromamba", "run", "-n", "base"]
    environment:
      - PYTHONUNBUFFERED=1
      - SUBJECT_ID=${SUBJECT_ID}
      - SESSION_HASH=${SESSION_HASH}
    command: 
      - "python"
      - "start.py"
      - "server"
      - "--backend=ATFCMBackend"
      - "--domain-files"
      - "atfcm_frontend/encoding.lp"
      - "atfcm_frontend/instance.lp"
      - "--ui-files"
      - "atfcm_frontend/ui.lp"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.backend-${SESSION_HASH}.entrypoints=web"
      - "traefik.http.routers.backend-${SESSION_HASH}.rule=PathPrefix(`/session/${SESSION_HASH}/api`)"
      - "traefik.http.middlewares.strip-api-${SESSION_HASH}.stripprefix.prefixes=/session/${SESSION_HASH}/api"
      - "traefik.http.routers.backend-${SESSION_HASH}.middlewares=strip-api-${SESSION_HASH}"
      - "traefik.http.services.backend-${SESSION_HASH}.loadbalancer.server.port=8000"
    volumes:
      - /root/ASPaeroFlow/telemetry_data:/app/telemetry_data

    networks:
      - default
      - proxy

  frontend:
    build:
      # Relative path traversing up 3 levels, then down into 2026
      context: ../ASPaeroFlow-XAI/angular_frontend
      dockerfile: Dockerfile
    depends_on:
      - clinguin-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend-${SESSION_HASH}.entrypoints=web"
      - "traefik.http.routers.frontend-${SESSION_HASH}.rule=PathPrefix(`/session/${SESSION_HASH}`)"
      - "traefik.http.middlewares.strip-ui-${SESSION_HASH}.stripprefix.prefixes=/session/${SESSION_HASH}"
      - "traefik.http.routers.frontend-${SESSION_HASH}.middlewares=strip-ui-${SESSION_HASH}"
      - "traefik.http.services.frontend-${SESSION_HASH}.loadbalancer.server.port=80"
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
